name: Build and Deploy Code

on: [push]
jobs:
  job1:
    runs-on: ububtu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to Dilip
        run: echo "Hello Dilip"
